In [1]:
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import prepare
import acquire
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Exercises
## Using the titanic data, in your classification-exercises repository, create a notebook, model.ipynb where you will do the following:

In [2]:
df= acquire.get_titanic_data()
df.head()

Unnamed: 0  passenger_id  survived  pclass     sex   age  sibsp  parch  \
0           0             0         0       3    male  22.0      1      0   
1           1             1         1       1  female  38.0      1      0   
2           2             2         1       3  female  26.0      0      0   
3           3             3         1       1  female  35.0      1      0   
4           4             4         0       3    male  35.0      0      0   

      fare embarked  class deck  embark_town  alone  
0   7.2500        S  Third  NaN  Southampton      0  
1  71.2833        C  First    C    Cherbourg      0  
2   7.9250        S  Third  NaN  Southampton      1  
3  53.1000        S  First    C  Southampton      0  
4   8.0500        S  Third  NaN  Southampton      1

In [3]:
titanic= prepare.prep_titanic(df)
titanic.head(2)

survived  pclass   age  sibsp  parch     fare  alone  sex_male  \
0         0       3  22.0      1      0   7.2500      0         1   
1         1       1  38.0      1      0  71.2833      0         0   

   embark_town_Queenstown  embark_town_Southampton  
0                       0                        1  
1                       0                        0

In [9]:
# Deleting the missing values
titanic.dropna(inplace=True)

### What is your baseline prediction? 

In [10]:
titanic.survived.value_counts()

0    424
1    288
Name: survived, dtype: int64

My baseline prediction is did not survive because 549 passengers did not survive.

### What is your baseline accuracy? <br><br>

In [11]:
baseline_accuracy = (1 - titanic.survived.mean())
baseline_accuracy

0.5955056179775281

### Fit the decision tree classifier to your training sample and transform (i.e. make predictions on the training sample)

In [15]:
X = titanic[['pclass','age','fare','sibsp','parch']]
y = titanic[['survived']]

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .20, random_state = 719)

X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size = .30, random_state = 719)

print("X train: ", X_train.shape, ", X validate: ", X_validate.shape, ", X test: ", X_test.shape)
print("Y train: ", y_train.shape, ", Y validate: ", y_validate.shape, ", Y test: ", y_test.shape)

X train:  (398, 5) , X validate:  (171, 5) , X test:  (143, 5)
Y train:  (398, 1) , Y validate:  (171, 1) , Y test:  (143, 1)


In [13]:
X_train

pclass   age      fare  sibsp  parch
689       1  15.0  211.3375      0      1
794       3  25.0    7.8958      0      0
467       1  56.0   26.5500      0      0
737       1  35.0  512.3292      0      0
741       1  36.0   78.8500      1      0
..      ...   ...       ...    ...    ...
715       3  19.0    7.6500      0      0
699       3  42.0    7.6500      0      0
785       3  25.0    7.2500      0      0
203       3  45.5    7.2250      0      0
142       3  24.0   15.8500      1      0

[398 rows x 5 columns]

In [14]:
#Baseline for our model
survival_rate = (1- y_train.survived.mean())
survival_rate

0.5904522613065326

### Evaluate your in-sample results using the model score, confusion matrix, and classification report.

In [21]:
# Create the Decision Tree Object
clf = DecisionTreeClassifier(max_depth=3, random_state=719)
# Fit the model to the training data
clf = clf.fit(X_train, y_train)

In [25]:
# make prediction on train obeservations
y_pred = clf.predict(X_train)
y_pred[0:5] 

array([1, 0, 0, 1, 1])

In [27]:
y_pred_prob = clf.predict_proba(X_train)
y_pred_prob[0:5]

array([[0.24107143, 0.75892857],
       [0.76923077, 0.23076923],
       [0.5952381 , 0.4047619 ],
       [0.24107143, 0.75892857],
       [0.24107143, 0.75892857]])

In [20]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
      .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.76


In [29]:
# confusion matrix
confusion_matrix(y_train, y_pred)

array([[208,  27],
       [ 69,  94]])

In [30]:
# classification report
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.89      0.81       235
           1       0.78      0.58      0.66       163

    accuracy                           0.76       398
   macro avg       0.76      0.73      0.74       398
weighted avg       0.76      0.76      0.75       398



### Compute: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

### Run through steps 2-4 using a different max_depth value.

### Which model performs better on your in-sample data?

### Which model performs best on your out-of-sample data, the validate set?